/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQuerySuggestionBeanApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   suggestionBeanApi/v1
// Description:
//   This is an API
// Classes:
//   GTLQuerySuggestionBeanApi (3 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLSuggestionBeanApiSuggestionBean;

@interface GTLQuerySuggestionBeanApi : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSString *question;

#pragma mark - Service level methods
// These create a GTLQuerySuggestionBeanApi object.

// Method: suggestionBeanApi.getAnswer
//  Authorization scope(s):
//   kGTLAuthScopeSuggestionBeanApiUserinfoEmail
// Fetches a GTLSuggestionBeanApiSuggestionBean.
+ (instancetype)queryForGetAnswerWithQuestion:(NSString *)question;

// Method: suggestionBeanApi.getSuggestionBean
//  Authorization scope(s):
//   kGTLAuthScopeSuggestionBeanApiUserinfoEmail
// Fetches a GTLSuggestionBeanApiSuggestionBean.
+ (instancetype)queryForGetSuggestionBeanWithIdentifier:(NSString *)identifier;

// Method: suggestionBeanApi.insertSuggestionBean
//  Authorization scope(s):
//   kGTLAuthScopeSuggestionBeanApiUserinfoEmail
// Fetches a GTLSuggestionBeanApiSuggestionBean.
+ (instancetype)queryForInsertSuggestionBeanWithObject:(GTLSuggestionBeanApiSuggestionBean *)object;

@end
