/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSuggestionBeanApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   suggestionBeanApi/v1
// Description:
//   This is an API

#import "GTLSuggestionBeanApiConstants.h"

#import "GTLSuggestionBeanApiSuggestionBean.h"

#import "GTLQuerySuggestionBeanApi.h"
#import "GTLServiceSuggestionBeanApi.h"
